name: CodeChecks

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
        db:
          - mysql
          - sqlite

    name: PHP ${{ matrix.php }} ${{ matrix.db }} tests

    env:
      DB_DRIVER: ${{ matrix.db }}
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MySQL
        if: ${{ matrix.db == 'mysql' }}
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'SHOW VARIABLES LIKE "version%";' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} mysql
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Composer
        run: composer install --no-progress

      - name: Check CS
        run: vendor/bin/ecs

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        env:
          INTEGRATION_ENABLED: 1

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"
